"""UI Images for the bot"""

UI_IMAGES = {
    "main_menu": "https://i.imgur.com/JhoomMainMenu.jpg",
    "commands_menu": "https://i.imgur.com/JhoomCommands.jpg",
    "playlist": "https://i.imgur.com/JhoomPlaylist.jpg",
    "diagnostics": "https://i.imgur.com/JhoomDiagnostics.jpg",
    "admin": "https://i.imgur.com/JhoomAdmin.jpg",
    "error": "https://i.imgur.com/JhoomError.jpg",
    "success": "https://i.imgur.com/JhoomSuccess.jpg",
    "player": "https://i.imgur.com/JhoomPlayer.jpg",
    "radio": "https://i.imgur.com/JhoomRadio.jpg",
    "settings": "https://i.imgur.com/JhoomSettings.jpg",
    "volume": "https://i.imgur.com/JhoomVolume.jpg",
    "quality": "https://i.imgur.com/JhoomQuality.jpg",
    "language": "https://i.imgur.com/JhoomLanguage.jpg",
    "notifications": "https://i.imgur.com/JhoomNotifications.jpg",
    "channel": "https://i.imgur.com/JhoomChannel.jpg",
    "speed": "https://i.imgur.com/JhoomSpeed.jpg",
    "download": "https://i.imgur.com/JhoomDownload.jpg",
    "loop": "https://i.imgur.com/JhoomLoop.jpg",
    "shuffle": "https://i.imgur.com/JhoomShuffle.jpg",
    "seek": "https://i.imgur.com/JhoomSeek.jpg",
    "broadcast": "https://i.imgur.com/JhoomBroadcast.jpg",
    "startup": "https://i.imgur.com/JhoomStartup.jpg",
    "queue": "https://i.imgur.com/JhoomQueue.jpg",
    "block": "https://i.imgur.com/JhoomBlock.jpg",
    "blacklist": "https://i.imgur.com/JhoomBlacklist.jpg",
    "gbans": "https://i.imgur.com/JhoomGBans.jpg",
    "license": "https://i.imgur.com/JhoomLicense.jpg",
    "revamp": "https://i.imgur.com/JhoomRevamp.jpg",
    "sultan": "https://i.imgur.com/JhoomSultan.jpg",
    "spiral": "https://i.imgur.com/JhoomSpiral.jpg"
}